const {chromium}=require('playwright-core');const {validURL}=require('./worker.cjs');const dns=require('node:dns/promises');const ipaddr=require('ipaddr.js');
function publicIP(raw){try{let ip=ipaddr.parse(raw);if(ip.kind()==='ipv6'&&ip.isIPv4MappedAddress())ip=ip.toIPv4Address();return ip.range()==='unicast';}catch{return false;}}
function vacancyText(text,heading){const start=heading?text.indexOf(heading):-1;return (start>=0?text.slice(start):'').split(/Lowongan Lainnya Untukmu|Similar jobs|Recommended jobs/)[0].trim();}
function sessionStatus({account,login,challenge}){return challenge?'portal_blocked':login?'login_required':account?'authenticated':'authentication_unverified';}
async function read({portal,url,kind,limit=3},endpoint='http://[::1]:9222'){
 const v=await fetch(endpoint+'/json/version',{signal:AbortSignal.timeout(5000)}).then(r=>r.json());const e=new URL(endpoint);const ws=new URL(v.webSocketDebuggerUrl);ws.host=e.host;
 const browser=await chromium.connectOverCDP(ws.toString(),{timeout:10000});let page;
 const resolved=new Map();try{page=await browser.contexts()[0].newPage();await page.route('**/*',async route=>{const r=route.request();let u;try{u=new URL(r.url())}catch{return route.abort();}if(u.protocol!=='https:')return route.abort();try{if(!resolved.has(u.hostname))resolved.set(u.hostname,await dns.lookup(u.hostname,{all:true}));if(!resolved.get(u.hostname).every(a=>publicIP(a.address)))return route.abort();}catch{return route.abort();}if(r.isNavigationRequest()&&r.frame()===page.mainFrame()&&u.hostname!==(portal==='glints'?'glints.com':'id.jobstreet.com'))return route.abort();return route.continue();});
 const response=await page.goto(url,{waitUntil:'domcontentloaded',timeout:45000});await page.waitForTimeout(6000);
 if(!validURL(portal,page.url(),kind))return {status:'login_required',portal,authentication:'login_required',url:page.url(),collected_at:new Date().toISOString()};
 const state=await page.evaluate(portal=>{const anchors=[...document.querySelectorAll('a')];const account=anchors.some(a=>portal==='glints'?a.getAttribute('href')==='/id/profile':/\/profile\/me/.test(a.href)&&a.innerText.trim().length>0);const login=anchors.some(a=>/^(log in|sign in|masuk)$/i.test(a.innerText.trim()));const challenge=/verify you are human|checking your browser|access denied|captcha/i.test(document.body.innerText.slice(0,2000));return {account,login,challenge};},portal);
 const authentication=sessionStatus(state);const base={portal,url:page.url().split('?')[0].split('#')[0],authentication,collected_at:new Date().toISOString(),http_status:response?.status()};if(authentication!=='authenticated')return {...base,status:authentication};
 if(kind==='discover'){const links=await page.locator('a').evaluateAll(a=>a.map(e=>({title:e.innerText.trim(),url:e.href})));const seen=new Set();return {...base,status:'ok',jobs:links.filter(x=>{if(!validURL(portal,x.url,'detail')||!x.title)return false;const u=new URL(x.url);u.search='';u.hash='';x.url=u.href;if(seen.has(x.url))return false;seen.add(x.url);return true;}).slice(0,limit)};}
 const heading=await page.locator('h1').first().innerText({timeout:5000}).catch(()=>null);const text=vacancyText(await page.locator('body').innerText(),heading);if(/job.*(expired|no longer available)|lowongan.*(ditutup|tidak tersedia)/i.test(text.slice(0,3000)))return {...base,status:'expired'};
 const structured=await page.locator('script[type="application/ld+json"]').allTextContents();return {...base,status:heading&&text.length>500?'ok':'details_incomplete',heading,page_title:await page.title(),text:text.slice(0,40000),text_truncated:text.length>40000,structured_data:structured.map(t=>{try{return JSON.parse(t)}catch{return null;}}).filter(Boolean),evidence:{url:base.url,excerpt:text.slice(0,1500)}};
 }finally{if(page)await page.close();await browser.close();}}
module.exports={sessionStatus,read,publicIP,vacancyText};
